//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Store.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class webshopEntities : DbContext
    {
        public webshopEntities()
            : base("name=webshopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categories> categories { get; set; }
        public virtual DbSet<count> count { get; set; }
        public virtual DbSet<news> news { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<sold> sold { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<cart> cart { get; set; }
    }
}
