//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sold
    {
        public int idSold { get; set; }
        public string UserMail { get; set; }
        public string ProductName { get; set; }
        public string Price { get; set; }
        public System.DateTime DateSold { get; set; }
        public string Address { get; set; }
    }
}
